version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/src/worker/yaxpeax-x86"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
